apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: data-strimzi-devtest-zookeeper-1
  namespace: strimzi-kafka
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: strimzi-devtest-zookeeper-1
