apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-devtest
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 34003
        type: nodeport
        tls: false
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 3Gi
        cpu: "2"
    jvmOptions:
      -Xms: 512m
      -Xmx: 2g
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: persistent-claim
      size: 12Gi
      deleteClaim: false
      class: managed-nfs-storage
  zookeeper:
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    replicas: 3
    resources:
      requests:
        memory: 512Mi
        cpu: "1"
      limits:
        memory: 1Gi
        cpu: "1"
    jvmOptions:
      -Xms: 512m
      -Xmx: 1g
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: false
      class: managed-nfs-storage
  entityOperator:
    topicOperator: {}
    userOperator: {}
