apiVersion: v1
kind: PersistentVolume
metadata:
  name: strimzi-devtest-kafka-1
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 12Gi
  nfs:
    path: /strimzi/strimzi-kafka-1
    server: nfs.test.com
  mountOptions: ["nolock"]
  persistentVolumeReclaimPolicy: Retain
