apiVersion: v1
kind: PersistentVolume
metadata:
  name: strimzi-devtest-zookeeper-2
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /strimzi/strimzi-zookeeper-2
    server: nfs.test.com
  mountOptions: ["nolock"]
  persistentVolumeReclaimPolicy: Retain
